---
language: node_js

node_js:
  - 'node'
  - '12'
  - '11'
  - '10'

sudo: false

# env:
#   - workerCount=3 timeout=60000

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

git:
  depth: 1

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install

after_success: npm run coverage
