---
language: node_js

node_js:
  - node
  - 12
  - 11
  - 10

sudo: false

stages:
  - lint
  - test
  - name: deploy
    if: |
      branch = master AND
      type NOT IN (pull_request)

install:
  - npm ci

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: deploy
      script:
        - npm run compile
        - npm publish
      deploy:
        provider: npm
        email: eric.s.crosson@utexas.edu
        api_key: $NPM_TOKEN
        on:
          tags: true

after_success:
  - npm run coverage
